# Bare `python` was upstream's, and on this host it resolves to the system interpreter,
# which has none of this. Host work runs through the repo venv (owner decision
# 2026-08-01: `.venv/bin/python`, not `uv run` — `uv run` binds to pyproject and ignores
# the inline PEP 723 blocks the scripts carry). Override for a container: `make PY=python`.
PY ?= .venv/bin/python

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

# `create-package` was DELETED 2026-08-06 (G-3). It ran `twine upload dist/*` against
# metadata that still said `name="matcha-tts"`, so one `make create-package` would have
# published this fork to PyPI under upstream's package name. We do not publish to PyPI at
# all — the model ships as checkpoints on Hugging Face — so there is nothing to replace it
# with. `Private :: Do Not Upload` in pyproject is the belt to this braces.

format: ## Run pre-commit hooks
	$(PY) -m pre_commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	$(PY) -m pytest -k "not slow"

test-full: ## Run all tests
	$(PY) -m pytest

# Training does NOT run from here. It runs in the ROCm container, which owns the GPU and
# supplies the checkpoint/resume overrides that the repo configs do not:
#   SONORA_EXPERIMENT=<name> docker compose -f AI-Lab-AMD/docker-compose.yml \
#       --profile training up -d sonora_training
# See notes/training-operations.md. The two `train-ljspeech` targets were upstream's and
# would have started a bare run on the host with every-100-epochs checkpointing.

vocalizer: ## Start the Sonora Vocalizer (the vetting surface; CPU, port 7862)
	$(PY) vocalizer.py

# `start_app` (matcha/app.py) was removed 2026-08-06 — it launches with share=True, a
# public tunnel from a machine holding unreleased checkpoints. Use `make vocalizer`.
